name: Allure Report Deployment

on:
  workflow_run:
    workflows: ["质量门禁-校验用例通过率"]
    types:
      - completed

jobs:
  allure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Download Allure Report
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: allure-report
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}