name: 接口自动化CI测试
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置Python3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 执行pytest自动化，收集Allure结果（带质量门禁）
        run: pytest test_api_data_driven.py -v --alluredir=allure-results --reruns 2 --reruns-delay 2


      - name: 归档Allure原始结果
        uses: actions/upload-artifact@v4
        with:
          name: allure-result-data
          path: allure-results
